local console = require("../src/params")

local err, params = console.parse_params("iii")
assert(err == nil)
assert(params[1].name == false)
assert(params[1].type == "i")
assert(params[1].optional == false)
assert(params[2].name == false)
assert(params[2].type == "i")
assert(params[2].optional == false)
assert(params[3].name == false)
assert(params[3].type == "i")
assert(params[3].optional == false)

err, params = console.parse_params("i[seconds]")
assert(err == nil)
assert(params[1].name == "seconds")
assert(params[1].type == "i")
assert(params[1].optional == false)


err, params = console.parse_params("i[seconds]s[name]")
assert(err == nil)
assert(params[1].name == "seconds")
assert(params[1].type == "i")
assert(params[1].optional == false)
assert(params[2].name == "name")
assert(params[2].type == "s")
assert(params[2].optional == false)

-- -- TODO: spaces
-- err, params = console.parse_params("i[seconds] s[name]")
-- assert(err == nil)
-- assert(params[1].name == "seconds")
-- assert(params[1].type == "i")
-- assert(params[1].optional == false)
-- assert(params[2].name == "name")
-- assert(params[2].type == "s")
-- assert(params[2].optional == false)
