local console = require("../src/params")
local assert_eq = require("simple.assert").assert_eq

local err, params = console.parse_params("iii")
assert_eq(nil, err)
assert_eq(false, params[1].name)
assert_eq("i", params[1].type)
assert_eq(false, params[1].optional)
assert_eq(false, params[2].name)
assert_eq("i", params[2].type)
assert_eq(false, params[2].optional)
assert_eq(false, params[3].name)
assert_eq("i", params[3].type)
assert_eq(false, params[3].optional)

err, params = console.parse_params("i[seconds]")
assert_eq(nil, err)
assert_eq("seconds", params[1].name)
assert_eq("i", params[1].type)
assert_eq(false, params[1].optional)

err, params = console.parse_params("i[seconds]s[name]")
assert_eq(nil, err)
assert_eq("seconds", params[1].name)
assert_eq("i", params[1].type)
assert_eq(false, params[1].optional)
assert_eq("name", params[2].name)
assert_eq("s", params[2].type)
assert_eq(false, params[2].optional)

err, params = console.parse_params("i[seconds] s[name]")
assert_eq(nil, err)
assert_eq("seconds", params[1].name)
assert_eq("i", params[1].type)
assert_eq(false, params[1].optional)
assert_eq("name", params[2].name)
assert_eq("s", params[2].type)
assert_eq(false, params[2].optional)

err, params = console.parse_params("i[seconds] ?s[name]")
assert_eq(nil, err)
assert_eq("seconds", params[1].name)
assert_eq(false, params[1].optional)
assert_eq("name", params[2].name)
assert_eq(true, params[2].optional)

err, params = console.parse_params("i?s")
assert_eq(nil, err)
assert_eq(false, params[1].name)
assert_eq(false, params[1].optional)
assert_eq(false, params[2].name)
assert_eq(true, params[2].optional)

err, params = console.parse_params("?s")
assert_eq(nil, err)
assert_eq(false, params[1].name)
assert_eq(true, params[1].optional)

err, params = console.parse_params("si[seconds]")
assert_eq(nil, err)
assert_eq(false, params[1].name)
assert_eq(false, params[1].optional)
assert_eq("seconds", params[2].name)
assert_eq(false, params[2].optional)

err, params = console.parse_params("i[[[seconds]")
assert_eq("unexpected [", err)

err, params = console.parse_params("i[seconds]]")
assert_eq("unsupported parameter type ']'", err)

err, params = console.parse_params("ixi")
assert_eq("unsupported parameter type 'x'", err)

err, params = console.parse_params("i[client id]")
assert_eq(nil, err)
assert_eq("client id", params[1].name)

err, params = console.parse_params("?r[player name]")
assert_eq(nil, err)
assert_eq("player name", params[1].name)
assert_eq(true, params[1].optional)
assert_eq("r", params[1].type)

err, params = console.parse_params("?s['gametimer'|'broadcast'|'both'|'none'|'cycle']")
assert_eq(nil, err)
assert_eq("'gametimer'|'broadcast'|'both'|'none'|'cycle'", params[1].name)

err, params = console.parse_params("?i['0'|'1']")
assert_eq(nil, err)
assert_eq("'0'|'1'", params[1].name)

err, params = console.parse_params("?ii")
assert_eq("optional can not be followed by non optional", err)

err, params = console.parse_params("i?ii")
assert_eq("optional can not be followed by non optional", err)

err, params = console.parse_params("i[id] ?i[opt] i[foo]")
assert_eq("optional can not be followed by non optional", err)
